### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by KeksUngegessen** [KeksUngegessen/IOTA-Digital-Student-ID#4]
Es soll recherchiert werden, was der [IOTA Tangle](https://wiki.iota.org/learn/about-iota/an-introduction-to-iota), seine Funktion  und Architektur ist, wie er benutzt und wie letztlich auf ihm entwickelt werden kann. Anschließend sollen die Ergebnisse kurz und knapp präsentierbar gemacht und eine (grobe) Anwendungsarchitektur für dieses Projekt erstellt werden.

## Arbeitsschritte

- [ ] Fachbegriffe recherchieren
  - [ ] DID: [IOTA](https://wiki.iota.org/identity.rs/introduction), [W3C](https://www.w3.org/TR/did-core/)
  - [ ] [DID Document](https://www.w3.org/TR/did-core/#data-model)
  - [ ] [Verifiable Credentials](https://www.w3.org/TR/vc-data-model/)
  - [ ] Verifier und [Authentifizierung](https://www.w3.org/TR/did-core/#authentication)
  - [ ] in den #3 einpflegen
- [ ] Funktionsweise des [Tangle](https://wiki.iota.org/learn/about-iota/an-introduction-to-iota) recherchieren
  - [ ] [IOTA DID Method Implementation](https://wiki.iota.org/identity.rs/specs/did/iota_did_method_spec)
  - [ ] in den #3 einpflegen
- [ ] [Entwicklung auf dem Tangle](https://wiki.iota.org/iota.rs/overview) recherchieren
  - [ ] in den #3 einpflegen
- [ ] Anwendungsarchitektur visualisieren und in den #3 einpflegen
